use_frameworks!

target 'AZPinController_Example' do
  pod 'AZPinController', :path => '../'

  target 'AZPinController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
